# Generated by Django 5.1 on 2024-08-30 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wibu_catalog', '0014_product_inventory'),
        ('wibu_catalog', '0016_merge_20240830_1405'),
    ]

    operations = [
    ]
